# Add WIP labels for PRs that are set to be work-in-progress, no other label will be added.
addWipLabel: true

# Configuration for labels, set ignore to true to skip adding label
labels:
  wip:
    name: "🚥 작업 진행중"
    color: "#c5def5"
    description: "Still work-in-progress, please don't review and don't merge"
    ignore: false
  unreviewed: 
    name: "👀 리뷰 요청"
    color: "#E075E4"
    description: "Pull Request is not reviewed yet"
    ignore: false
  approved: 
    name: "👏 Merge 진행"
    color: "#A2D53F"
    description: "Pull Request has been approved and can be merged"
    ignore: false
  needsMoreApprovals: 
    name: "🔍 추가 승인 필요"
    color: "#334796"
    description: "Pull Request needs more approvals"
    ignore: false
  changesRequested:
    name: "📣 수정 요청"
    color: "#AA2626"
    description: "Pull Request needs changes before it can be reviewed again"
    ignore: false
  merged: 
    name: "👍 Merge 완료"
    color: "#6F42C1"
    description: "Pull Request has been merged successfully"
    ignore: false

# A list of reviewers whose names should be added as tags to PRs, 
# as long as their review is requested.
#
# user: GitHub username
#   name: Title of label
#   color: Color of label

# Example
# reviewers:
#   userA:
#     name: "User A"
#     color: "#000000"
